package org.sackfix.fix50sp2

import org.sackfix.field._
import org.sackfix.common.validated.fields.{SfFixComponent, SfFixDecoder, SfFixFieldsToAscii, SfFixRenderable}
import org.sackfix.common.message.SfRepeatingGroupCountException
import scala.annotation.tailrec
import scala.collection.immutable.HashSet
import scala.collection.mutable.ArrayBuffer


/**
  * Generated by SackFix code generator on 20210314
  * Source specification was read from:
  *   /quickfixj1.6.0/FIX50SP2.xml
  */
case class AffectedOrdGrpComponent(noAffectedOrdersField:Option[NoAffectedOrdersField]=None,
                                   affectedOrdersGroups: Option[List[AffectedOrdersGroup]]=None) extends SfFixComponent  with SfFixRenderable with SfFixFieldsToAscii {
  if (noAffectedOrdersField.map(_.value).getOrElse(0) != affectedOrdersGroups.map(_.size).getOrElse(0))
    throw SfRepeatingGroupCountException(NoAffectedOrdersField.TagId,noAffectedOrdersField.map(_.value).getOrElse(0), affectedOrdersGroups.map(_.size).getOrElse(0))

  override lazy val fixStr : String = appendFixStr().toString
  override def appendFixStr(b:StringBuilder = new StringBuilder): StringBuilder = format(formatForFix, b)

  override def toString():String = appendStringBuilder().toString()
  def appendStringBuilder(b:StringBuilder = new StringBuilder) : StringBuilder = format(formatForToString, b)

  def format( fmt: ((StringBuilder,SfFixRenderable)=>Unit), b:StringBuilder = new StringBuilder()): StringBuilder = {
    noAffectedOrdersField.foreach(fmt(b,_))
    affectedOrdersGroups.getOrElse(List.empty).foreach(fmt(b,_))
    b
  }

}
     
object AffectedOrdGrpComponent extends SfFixDecoder {

  override val MandatoryFields = HashSet[Int]()

  override def isMandatoryField(tagId:Int) : Boolean = {
    MandatoryFields.contains(tagId)  || 
    AffectedOrdersGroup.isMandatoryField(tagId)
  }

  override val OptionalFields = HashSet[Int](
    NoAffectedOrdersField.TagId)

  override def isOptionalField(tagId:Int) : Boolean = {
    OptionalFields.contains(tagId)  || 
    AffectedOrdersGroup.isOptionalField(tagId)
  }

  override def isFieldOf(tagId:Int) : Boolean = isMandatoryField(tagId) || isOptionalField(tagId)  || 
    AffectedOrdersGroup.isFieldOf(tagId)

   override lazy val RepeatingGroupsTags = HashSet[Int](
    NoAffectedOrdersField.TagId)
  
      
  override def isFirstField(tagId:Int) : Boolean = AffectedOrdersGroup.isFirstField(tagId) 

  def decode(flds: Seq[Tuple2[Int, Any]], startPos:Int = 0):Option[AffectedOrdGrpComponent] = {
    val (pos, myFields, nextTagPosLookup) = extractMyFieldsAndPopulatePositions(false, flds, startPos)
    validateMandatoryFieldsPresent(myFields)

    if (myFields.nonEmpty) {
      Some(AffectedOrdGrpComponent(myFields.get(NoAffectedOrdersField.TagId).flatMap(f=>NoAffectedOrdersField.decode(f)),
        if (nextTagPosLookup.contains(NoAffectedOrdersField.TagId)) AffectedOrdersGroup.decode(flds, nextTagPosLookup(NoAffectedOrdersField.TagId)) else None))
    } else None
  }

    
}
     